package com.ailms.common.dto;

import java.util.List;

/** A single structured quiz item generated by the QuestionGenerationAgent. */
public record QuizItem(
    String question, String type, List<String> options, String answer, String explanation) {}